sudo: false
os:
  - linux
language: node_js
node_js:
  - "4"
  - "5"
env:
  matrix:
    - TEST_SUITE=unit:node
matrix:
  include:
    - node_js: "4"
      env: TEST_SUITE=lint
script: npm run $TEST_SUITE
